### ISSUE TITLE
Using Argument#taggedUnion throws `TypeError: Cannot read property 'handler' of undefined`

### ISSUE THREAD

**Issue by not-so-smart** [discord-akairo/discord-akairo#169]
basically #94 but with `taggedUnion`

```js
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'handler' of undefined
    at typeFn (Argument.js:546:56)
    at Function.cast (Argument.js:370:23)
    at Argument.typeFn (Argument.js:586:44)
    at Function.cast (Argument.js:370:23)
    at Argument.cast (Argument.js:194:25)
    at Argument.process (Argument.js:169:32)
    at ArgumentRunner.runPhrase (ArgumentRunner.js:138:25)
    at ArgumentRunner.runOne (ArgumentRunner.js:100:22)
    at ArgumentRunner.run (ArgumentRunner.js:61:36)
```
example:
```js
export default class LookupCommand extends Command {
    constructor() {
        super('find', {
            aliases: ['find', 'f'],
            args: [
                {
                    id: 'query',
                    type: Argument.taggedUnion('user', 'member')
                }
            ]
        });
    }

    async exec(message: Message, args: Object) {
        console.log(args);
    }
}
```

**Comment by not-so-smart** [comment]
also this might be somewhat urgent because AFAIK the `taggedUnion` function doesn't work at all right now and will always throw that error regardless of usage
