### ISSUE TITLE
Using Argument#union with validated arguments throws `TypeError: Cannot read property 'handler' of undefined`

### ISSUE THREAD

**Issue by pizzafox** [discord-akairo/discord-akairo#94]
```js
TypeError: Cannot read property 'handler' of undefined
    at typeFn (/project/node_modules/discord-akairo/src/struct/commands/arguments/Argument.js:450:56)
    at Function.cast (/project/node_modules/discord-akairo/src/struct/commands/arguments/Argument.js:370:23)
    at Argument.typeFn (/project/node_modules/discord-akairo/src/struct/commands/arguments/Argument.js:412:44)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Function.cast (/project/node_modules/discord-akairo/src/struct/commands/arguments/Argument.js:371:39)
    at Argument.process (/project/node_modules/discord-akairo/src/struct/commands/arguments/Argument.js:169:21)
    at ArgumentRunner.run (/project/node_modules/discord-akairo/src/struct/commands/arguments/ArgumentRunner.js:61:25)
    at CommandHandler.handleDirectCommand (/project/node_modules/discord-akairo/src/struct/commands/CommandHandler.js:411:26)
    at CommandHandler.handle (/project/node_modules/discord-akairo/src/struct/commands/CommandHandler.js:377:23)
```

Occurs when the command argument's type is a union of a validated type

Example reproduction:

```js
Argument.union(
	'integer',
	Argument.validate('uppercase', (message, phrase) => (^[MDCLXVI]+$).test(phrase))
)
```

**Comment by perilstar** [comment]
Fixed in pull request #134

looks like a typo
